### ISSUE TITLE
Anchor box dimensions confusion

### ISSUE THREAD

**Issue by louisquinn** [flash10042/EfficientDet#2]
Hey thanks for the nice work on this implementation! I have a question about anchor boxes as there seems to be some inconsistencies with how the boxes are represented. 

* In some comments, it mentions anchors are in the format `[x, y, width, height]`. From the code it looks like however they are in the format: `[x_centre, y_centre, width, height]`?
* When generating the anchor "dims", they are stored as `[height, width]`, is that intentional? Also the calculation seems to be backwards, or do you represent aspect ratio 
 `height / width` in stead of `width / height`?
https://github.com/flash10042/EfficientDet/blob/049adc6227527571855c6bed1e780bfcc7bbf00b/model/anchors.py#L42
* Then, when computing the anchor/gt-box IOU, `to_corners` seems to specify that input box is shape `[x, y, width, height]`, which I'm assuming means `[x_centre, y_centre, width, height]`, but actually the boxes seem to be in the format: `[y_centre, x_centre, height width]`?
https://github.com/flash10042/EfficientDet/blob/049adc6227527571855c6bed1e780bfcc7bbf00b/model/utils.py#L16

**So my questions are this:**
* What is the intended box format of the anchors? https://github.com/flash10042/EfficientDet/blob/049adc6227527571855c6bed1e780bfcc7bbf00b/model/anchors.py#L71
* I assume the ground truth box should be in the format: `[x_centre, y_centre, width, height]`?

**Comment by flash10042** [comment]
Hey! It's been a while since I opened this repo, but I'll try to answer your questions.

> * What is the intended box format of the anchors?

I've checked a code and there is indeed a mistake. Height and width are misordered in the list.
https://github.com/flash10042/EfficientDet/blob/049adc6227527571855c6bed1e780bfcc7bbf00b/model/anchors.py#L42
It should look like this:
```
dims = tf.cast([width, height], tf.float32) 
```
So the final shape would be `[x, y, width, height]`. By the way, I believe `[x, y, width, height]` and `[x_centre, y_centre, width, height]` are the same.

But to be honest I don't think it's a big deal in this case exactly, because for the default aspect ratios we will receive identical results for both cases.

> * I assume the ground truth box should be in the format: [x_centre, y_centre, width, height]?

You're right. You need to convert your ground truth bounding boxes to format `[x_centre, y_centre, width, height]`. You can use this function for it:
https://github.com/flash10042/EfficientDet/blob/049adc6227527571855c6bed1e780bfcc7bbf00b/model/utils.py#L7-L11

**Comment by louisquinn** [comment]
Hey @flash10042 thanks for your quick response!

Yep, everything makes sense and works well now! 
Also if you haven't seen it the TF-OD-API has a great tutorial on mining anchor box aspect ratios: https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/generate_ssd_anchor_box_aspect_ratios_using_k_means_clustering.ipynb

Anyway great job again on this implementation, its rare to see a lightweight simple one out there on GitHub that uses simple Keras structures.
